# Streamlit secrets in TOML format
[service_account]
type = "service_account"
project_id = "production-tracking-456908"
private_key_id = "10ab2344a90dca62d5d3ff42045f4bdd982a6465"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCd+ARhTbUaZ8I+
z/zsl49HXHHRMobDRXF3RXXobUWTmkKQ6sVVZYtI0Vamu9kgHqeTHbTQqoBJxbFI
YfAACSh4q7Oubea8quQ6/TRCppi2ShQJ25lo8Wb6HV3/D6w2HRq0CcCoEQcqV1yB
Is49WhyIe67IByIboHXeVKbeuMZJSGLyUa/oCzxOCuQV+QhirOKA1j9eTPCE1o5j
GDXvyAuzQZ9PNd3FmWK6f11unHWRGBqKbkbK6wnDsBbpA37iSOaLjjCJbZTtPA8Y
kjGtye9QApsDzyiJiRMX6fm1lkYP1WItMpmx2Nn553j7YFZm7foElKCIikhnpVeR
/Q/j8RsbAgMBAAECggEADnhKqmvBpEFkingR0ng66yNS16ykVIcWvYFS1hoK+Voe
29htgATfrSljzGfA8U9tiS0mRBuXdGp+nUM/W+QliBGDptLcA7nhqGz2LbQbS/iy
0jOtNJmG6xqSjXZu5LwQwfTHaChl0CFAJiISjeMkYZ92uKLn+GuKhcrvnXoudkWI
Hbrwsd+qavId8SSZqihXNNZ8fVguUNWijRsJGpw7ekkhmNsL796FjRpyHowLBQtZ
ZY0HcF6ne0hWB897gwIR0diY80ULYsKlVMLxJBXZF7ycBQUlo45Z+s2jvlqot33W
Hye/2H0GLuVVv9rO0AgF0TJM3TwxLpewmuW4SGqEtQKBgQDUvuvwH3D715IJBTZN
T1Dqr5s7ZGKoRezKZRpQ8NB1o1obu1Seai5eAkVbHXVY+70HFLAxchqzjQvyGAKe
RyNH9SF3O3Z+zxw6FxiNPBtnLQbZ8pgxyYmPXAzOq6ZcRJ5lEYE26+fzkQ3nU7GE
Vt8Rh0dCrwVj9Xv3gfjg3/uw1wKBgQC+FgqqF7+7D1tmh3ru7VIH2AnMHMxEonJc
FiVfwyT0sFHm5X6idWeA8aAyP9UTXlmzH7mtYK9O383blxPwlXNTEYGioXD8Nmp7
3oRB/7VndBHcgNQkudfyRm5ZIVwtONYhwt0PfkTS0zmXHp1xaqYIA/XZ4PN1Pws5
eRW1tyhrXQKBgGX5AXQ+TdSY9mmWcvnJe9qRw5FLQ7KumZpFrcCAPRs16joCp8Oq
14C+C+ppi1bUiz16oB2DOOM5RzGKaq7dID8ccycIfHq54SjC60S/O89PmMoc6vBq
TqJFl+n0ArCVP2roYgwmNS7dJ1HrHtp1HUT0l6aR576K6xmu1dFL6wNPAoGASv2p
IWeTJXouhemHD0GjLiMF4neuApnP4hJ+liQHrVzuQthhODh3KACrQYe7SRPc8XTf
rM3K+6QBs9MLc8uSHsB2UzG7wFS7d7jWlq8J4xGAhmxwxThoQFWW7STjF5gnqlQV
ICqhfkcEnmDenkMD03+0e0tq4OOJSxhA/1qN4KUCgYEAyLqtIlGyrKSBFstpjkYp
/aNo0XrPCdfHknnnWen6FKh3V5BfDyUe+iuay+aLcKDmW/AU5Cijl06BFCNFjGCF
GxlJSfuVol0gRF4S+GNwUXqvPTuIu+Bc0fT8ayryzLhUjTIjcQlVc4LoxQTVP11b
5Z9FD3rREkD4guudSlxxNxg=
-----END PRIVATE KEY-----
'''
client_email = "inventorytracking@production-tracking-456908.iam.gserviceaccount.com"
client_id = "108070711622921752309"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/inventorytracking%40production-tracking-456908.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# Theme settings for Streamlit secrets in TOML format
[theme]
primaryColor = "#2563eb"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#e5e7eb"
textColor = "#1e293b"
font = "sans serif"
